### ISSUE TITLE
Serde support not on crates.io

### ISSUE THREAD

**Issue by thomhuds** [PistonDevelopers/hematite_nbt#35]
I'd like to depend on the current version of this crate in my crate, which I plan to publish on crates.io. Will the current version be published soon or should I add a git submodule?

**Comment by atheriel** [comment]
I have to investigate whether I can release a new version, since I’m not the one who released the last one.

**Comment by bvssvni** [comment]
Publishing should not be a problem, since the PistonDevelopers team is added as owner.

**Comment by thomhuds** [comment]
Any updates?

**Comment by atheriel** [comment]
Version 0.4.0 [is now on crates.io](https://crates.io/crates/hematite-nbt), which includes full `serde` support. If you encounter any bugs, please file an issue!
