### ISSUE TITLE
Cargo fmt, Clippy, deprecation

### ISSUE THREAD

**Issue by Schuwi** [PistonDevelopers/hematite_nbt#49]
When compiling the project rustc emits a lot of warnings. Also the code format seems inconsistent with `cargo fmt`.
I would suggest running `cargo fmt`, `cargo clippy` and fixing the deprecated stuff.

I might get on this myself in the next few days. Just wanted to hear if there is any reason that speaks against this :)

**Comment by atheriel** [comment]
Don’t rush to do a cargo fmt run, since it has some drawbacks preserving git history. But I’d be happy to see deprecation warnings and other clippy lints fixed.

**Comment by Schuwi** [comment]
Oh, I just went to Google for solutions for some `cargo fmt` magic that doesn't affect the git history as much and after reading through an interesting thread I found a familiar name... :D

https://github.com/greshake/i3status-rust/issues/340

How would you feel about implementing a similar policy on this project ;)
I experience having to manually format my code and generally working with inconsistent code style as quite cumbersome.
I mean, it's not a huge deal but it's just one of those things that gets more and more annoying over time, so I'd be quite happy if a similar solution could be deployed here.

**Comment by atheriel** [comment]
Yep, I’m happy to do a similar thing for this project. But I will probably do it myself, in master, instead of via PR.
