### ISSUE TITLE
varint support

### ISSUE THREAD

**Issue by skairunner** [PistonDevelopers/hematite_nbt#58]
The [schematic format](https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-2.md#paletteObject) uses varint encoding to pack block data. It may be nice to have varint support directly in NBT.

**Comment by atheriel** [comment]
I'm not sure what you mean by this, exactly -- what is a "varint" in the context of NBT? Is the schematic format that you've linked to specific to that particular modding engine or is it part of Minecraft itself?

**Comment by skairunner** [comment]
It's not part of Minecraft itself, but rather defined by SpongePowered and
used commonly throughout the ecosystem. Varint in the context of schematics
is a simple bit-packing scheme. I might make a PR for it if it's in the
scope of NBT, since I had to write the code anyways.

**Comment by atheriel** [comment]
> It's not part of Minecraft itself, but rather defined by SpongePowered and
> used commonly throughout the ecosystem.

If that's the case then I believe it's out-of-scope for this crate, unfortunately. This project is purely devoted to the NBT format, not the particular ways it has been employed by the various servers and communities over the years. Your code might make for a nice standalone project, though!
