### ISSUE TITLE
ByteArray is not serialized correctly

### ISSUE THREAD

**Issue by skairunner** [PistonDevelopers/hematite_nbt#59]
If you serialize a ByteArray and inspect the generated binary, it'll be serialized as a List (0x09) of Bytes (0x01), which is incorrect, since it should actually be a ByteArray (0x07).

**Comment by atheriel** [comment]
This is a limitation of Serde; it can't guess what kind of list format you want without additional help. The [release notes](https://github.com/PistonDevelopers/hematite_nbt/releases/tag/v0.5.0) have an example of the annotation you will need to use, as implemented in #52.

**Comment by skairunner** [comment]
I'm directly constructing an NBT Value, with a ByteArray specified and it's
still outputting as a List of Bytes. Can I further annotate
Value::ByteArray or something?

**Comment by atheriel** [comment]
Can you provide an example?

**Comment by skairunner** [comment]
Something like this (probably won't compile):

```rust
let mut root = HashMap::new();
let blockdata: Vec<i8> = get_block_data();
root.insert("BlockData".to_string(), Value::ByteArray(blockdata));
Value::Compound(root)
```

And then attempting to serialize with:

```rust
nbt::to_writer(&mut file, &nbt_compound, None);
```

I would expect the explicitly specifying Value::ByteArray would mean serde would correctly serialize it as a TAG_ByteArray, but it still uses a List instead.

**Comment by atheriel** [comment]
`nbt::to_writer()` *does* use Serde (the source of the `Serialize` trait), which is the source of this issue -- although it's possible we can now fix this with the our own new annotations.

But you definitely want to be using [the `Blob` API](https://docs.rs/hematite-nbt/0.5.0/nbt/struct.Blob.html) instead if you are constructing `Value`s directly like your example.

**Comment by skairunner** [comment]
Either way, as I understand it there's not a good way to force serde to output properly if I'm using the 'generic' Value/Blob interfaces? In other words, that I'd have to write a struct with the serialize_with annotations?

**Comment by atheriel** [comment]
Serde cannot output the right thing, but `Blob` structs have their own writer methods that will.

**Comment by skairunner** [comment]
Okay, thank you!
