### ISSUE TITLE
Serializing Byte Arrays With NBT Serde

### ISSUE THREAD

**Issue by zedseven** [PistonDevelopers/hematite_nbt#64]
I'm using this crate to enable exporting to the [Litematica](https://github.com/maruohon/litematica) schematic format, and I've figured everything out except how to create blob array data (I'm not sure of the proper name).

![image](https://user-images.githubusercontent.com/25164338/120359646-6dd02400-c2f7-11eb-9c6f-e60afbaf2acd.png)
In the above screencap, the `BlockStates` field is what I'm interested in serializing to. `PreviewImageData` is the same type, but with integers rather than longs. Please note I'm not asking how these fields actually work, but rather how to serialize to their types from a Rust struct using the NBT Serde functionality.

Thank you!

**Comment by atheriel** [comment]
There is an example [in the release notes](https://github.com/PistonDevelopers/hematite_nbt/releases/tag/v0.5.0) that could be helpful.

**Comment by zedseven** [comment]
Ah, I didn't think to check the Releases tab for documentation. Thank you for your quick reply!

Also though I doubt it really matters, I had to use `#[serde(serialize_with="nbt::i64_array")]` instead of `#[serde(serialize_with="hematite_nbt::i64_array")]`.

Thanks for your work on this crate.

**Comment by atheriel** [comment]
It's not surprising, we don't really have much public documentation (but would happily accept contributions that added some). However, you can often search the issue tracker for this kind of thing, which would have turned up the relevant issues/PRs.
